# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/synapse_db
spring.datasource.username=postgres
spring.datasource.password=gdti5s11se


# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true